version: '3'
services:
  api:
    build: ./api
    ports:
    - "8000:8000"
    environment:
      - DB_HOST=db:27017
    networks:
      - local
  dashboard:
    build: ./dashboard
    ports:
    - "80:5000"
    environment:
      - API_HOST=http://api:8000
    networks:
      - local
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=db
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - "./db/:/docker-entrypoint-initdb.d"
      - "db-data:/data/db"
    networks:
      - local
volumes:
  db-data: {}
networks:
  local:
    driver: bridge
